SEED_JOBS = [
    {
        "title": "Junior Software Engineer",
        "company": "Hasura",
        "location": "Bengaluru, India",
        "work_type": "Hybrid",
        "salary": "₹8–14 LPA",
        "description": "Build and maintain backend services. Strong grasp of databases and algorithms required.",
        "skills": ["Python", "SQL", "Git", "REST APIs", "PostgreSQL", "Linux"],
    },
    {
        "title": "SDE Intern – Backend",
        "company": "Razorpay",
        "location": "Bengaluru, India",
        "work_type": "On-site",
        "salary": "₹60–80k/mo",
        "description": "Work on payment infra backend. Strong DSA and Java skills essential.",
        "skills": ["Java", "SQL", "Data Structures", "Git", "OOP", "Linux"],
    },
    {
        "title": "Data Engineering Intern",
        "company": "Freshworks",
        "location": "Chennai, India",
        "work_type": "Hybrid",
        "salary": "₹40–60k/mo",
        "description": "Build ETL pipelines and data models for product analytics.",
        "skills": ["Python", "SQL", "ETL", "Database design", "Data modeling"],
    },
    {
        "title": "Android Developer Intern",
        "company": "ShareChat",
        "location": "Bengaluru, India",
        "work_type": "Hybrid",
        "salary": "₹40–70k/mo",
        "description": "Build features for a 200M user social video platform.",
        "skills": ["Android Studio", "Java", "C++", "Mobile dev", "Git"],
    },
    {
        "title": "Competitive Programmer – Intern",
        "company": "CodeChef (Unacademy)",
        "location": "Bengaluru, India",
        "work_type": "Remote",
        "salary": "₹30–50k/mo",
        "description": "Create and review competitive programming problems. 300+ solve track preferred.",
        "skills": ["C++", "Python", "Dynamic Programming", "Graph Theory", "Algorithms"],
    },
    {
        "title": "Full Stack Developer Intern",
        "company": "Zoho",
        "location": "Chennai, India",
        "work_type": "On-site",
        "salary": "₹25–45k/mo",
        "description": "Work on enterprise SaaS features across the stack.",
        "skills": ["Java", "SQL", "HTML/CSS", "Git", "OOP", "REST APIs"],
    },
    {
        "title": "ML Engineer Intern",
        "company": "Sarvam AI",
        "location": "Bengaluru, India",
        "work_type": "Hybrid",
        "salary": "₹50–80k/mo",
        "description": "Fine-tune and evaluate LLMs for Indian language tasks.",
        "skills": ["Python", "NLP", "Machine Learning", "SQL", "Git"],
    },
    {
        "title": "DevOps Intern",
        "company": "Infosys",
        "location": "Pune, India",
        "work_type": "On-site",
        "salary": "₹20–35k/mo",
        "description": "Automate deployment pipelines. Linux and scripting skills required.",
        "skills": ["Linux", "Git", "Python", "CI/CD", "Shell scripting"],
    },
    {
        "title": "Database Administrator Intern",
        "company": "Oracle India",
        "location": "Hyderabad, India",
        "work_type": "On-site",
        "salary": "₹35–55k/mo",
        "description": "Assist in schema design and query optimization for enterprise clients.",
        "skills": ["SQL", "Database design", "ER diagrams", "MySQL", "DBMS"],
    },
    {
        "title": "Product Analyst Intern",
        "company": "Meesho",
        "location": "Bengaluru, India",
        "work_type": "Hybrid",
        "salary": "₹30–50k/mo",
        "description": "Use data to drive product decisions. Lean Canvas / business sense is a plus.",
        "skills": ["SQL", "Python", "Business modeling", "Analytics", "Market analysis"],
    },
    {
        "title": "Embedded Systems Intern",
        "company": "Texas Instruments India",
        "location": "Bengaluru, India",
        "work_type": "On-site",
        "salary": "₹40–60k/mo",
        "description": "Develop firmware and sensor integration for IoT hardware projects.",
        "skills": ["C", "C++", "Embedded systems", "Sensors", "Computer Architecture"],
    },
    {
        "title": "Open Source Contributor – GSoC",
        "company": "Google Summer of Code",
        "location": "Remote",
        "work_type": "Remote",
        "salary": "Stipend ~$3000",
        "description": "Contribute to established OSS orgs. Strong algorithmic background valued.",
        "skills": ["Python", "C++", "Git", "Algorithms", "Open source"],
    },
]
